name: NPM - Check source code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: "Check CLI code - NPM"
    runs-on: web3pi

    steps:
      - uses: actions/checkout@v4

      - name: Check if bun is installed
        run: |
          set -x
          bun --version

      - name: Install, lint and check
        run: | 
          bun install
          bun run lint
          bun run oxlint
          bun run format:check
          
