name: NPM - Build and test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  checks:
    name: "Check CLI code - NPM"
    runs-on: web3pi

    steps:
      - uses: actions/checkout@v4

      - name: Check if bun is installed
        run: |
          set -x
          bun --version

      - name: Install and build
        run: |
          bun install
          bun run build
